Command: make -j 10 flash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1355, in _main
    main()
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 815, in main
    esp = esp or get_default_connected_device(
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1240, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 726, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 602, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/esptool/reset.py", line 46, in __call__
    self.port.open()
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 338, in open
    self._update_rts_state()
  File "/home/student/.espressif/python_env/idf6.0_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 708, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_RTS_str)
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:67 (message):
  
  /home/student/.espressif/python_env/idf6.0_py3.10_env/bin/python;;/home/student/facultate/PM/proiect_esp32c6/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32c6
  failed.



make[3]: *** [CMakeFiles/flash.dir/build.make:70: CMakeFiles/flash] Error 1
make[2]: *** [CMakeFiles/Makefile2:2494: CMakeFiles/flash.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2501: CMakeFiles/flash.dir/rule] Error 2
make: *** [Makefile:286: flash] Error 2
